batch_size: 32
ddqn: true
default_root_dir: ./training_results/final-submission/baseline
device: cpu
dueling_dqn: true
env_config:
  include_walls_in_observations: true
  make_everything_static: false
  num_total_questions: 1000
  question_interval: 1
  question_prob: 1.0
  randomize_observations: objects
  rewards:
    correct: 1
    partial: 0
    wrong: 0
  room_size: l
  terminates_at: 99
env_str: room_env:RoomEnv-v2
epsilon_decay_until: 20000
gamma: 0.9
history_block_size: 24
max_epsilon: 1.0
min_epsilon: 0.1
nn_params:
  architecture: lstm
  embedding_dim: 128
  fuse_information: sum
  hidden_size: 128
  include_positional_encoding: true
  max_strength: 100
  max_timesteps: 100
  num_layers: 2
num_iterations: 20000
num_samples_for_results: 10
plotting_interval: 10
replay_buffer_size: 20000
run_handcrafted_baselines: true
run_test: true
target_update_interval: 10
test_seed: 0
train_seed: 5
warm_start: 2000.0
