batch_size: 32
capacity:
  episodic: 16
  episodic_agent: 0
  semantic: 16
  semantic_map: 0
  short: 1
ddqn: true
default_root_dir: ./training_results/
device: cpu
dueling_dqn: true
env_config:
  include_walls_in_observations: true
  make_everything_static: false
  num_total_questions: 1000
  question_interval: 1
  question_prob: 1.0
  randomize_observations: objects
  rewards:
    correct: 1
    partial: 0
    wrong: 0
  room_size: l
  terminates_at: 99
env_str: room_env:RoomEnv-v2
epsilon_decay_until: 10000
gamma: 0.9
max_epsilon: 1.0
min_epsilon: 0.1
mm_agent_path: training_results/final-submission/2024-01-17 10:41:27.401733/agent.pkl
mm_policy: neural
nn_params:
  architecture: lstm
  embedding_dim: 64
  fuse_information: sum
  hidden_size: 64
  include_positional_encoding: true
  make_categorical_embeddings: false
  max_strength: 100
  max_timesteps: 100
  memory_of_interest:
  - episodic
  - semantic
  num_layers: 2
  v1_params: null
  v2_params: {}
num_iterations: 10000
num_samples_for_results: 10
plotting_interval: 10
pretrain_semantic: false
qa_policy: episodic_semantic
replay_buffer_size: 10000
run_handcrafted_baselines:
- explore: random
  mm: random
  pretrain_semantic: false
  qa: episodic_semantic
- explore: random
  mm: random
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
- explore: avoid_walls
  mm: random
  pretrain_semantic: false
  qa: episodic_semantic
- explore: avoid_walls
  mm: random
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
- explore: random
  mm: episodic
  pretrain_semantic: false
  qa: episodic_semantic
- explore: random
  mm: episodic
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
- explore: avoid_walls
  mm: episodic
  pretrain_semantic: false
  qa: episodic_semantic
- explore: avoid_walls
  mm: episodic
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
- explore: random
  mm: semantic
  pretrain_semantic: false
  qa: episodic_semantic
- explore: random
  mm: semantic
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
- explore: avoid_walls
  mm: semantic
  pretrain_semantic: false
  qa: episodic_semantic
- explore: avoid_walls
  mm: semantic
  pretrain_semantic: exclude_walls
  qa: episodic_semantic
run_test: true
target_update_interval: 10
test_seed: 4
train_seed: 9
warm_start: 1000.0
