num_iterations: 4096
replay_buffer_size: 16
batch_size: 4
capacity:
  episodic: 16
  semantic: 16
  short: 1
env_str: room_env:RoomEnv-v1
epsilon_decay_until: 32
gamma: 0.65
max_epsilon: 1.0
min_epsilon: 0.1
nn_params:
  embedding_dim: 32
  hidden_size: 64
  include_human: sum
  n_actions: 3
  num_layers: 2
num_samples_for_results: 10
plotting_interval: 10
pretrain_semantic: false
run_test: true
run_validation: true
target_update_rate: 10
test_seed: 42
train_seed: 42
device: cpu
