env_str: room_env:RoomEnv-v1
max_epsilon: 1.0
min_epsilon: 0.1
epsilon_decay_until: 2048
gamma: 0.65
capacity:
  episodic: 16
  semantic: 16
  short: 1
nn_params:
  hidden_size: 64
  num_layers: 2
  n_actions: 3
  embedding_dim: 32
  include_human: sum
num_iterations: 1024
replay_buffer_size: 512
batch_size: 128
target_update_rate: 10
pretrain_semantic: false
run_validation: true
run_test: true
num_samples_for_results: 10
train_seed: 5
plotting_interval: 10
device: cpu
test_seed: 0
