env_str: room_env:RoomEnv-v2
num_iterations: 20000
replay_buffer_size: 20000
warm_start: 2000.0
batch_size: 32
target_update_interval: 10
epsilon_decay_until: 20000
max_epsilon: 1.0
min_epsilon: 0.1
gamma: 0.9
history_block_size: 6
nn_params:
  architecture: lstm
  hidden_size: 128
  num_layers: 2
  embedding_dim: 128
  fuse_information: sum
  include_positional_encoding: true
  max_timesteps: 100
  max_strength: 100
run_test: true
num_samples_for_results: 10
plotting_interval: 10
train_seed: 9
test_seed: 4
device: cpu
env_config:
  question_prob: 1.0
  terminates_at: 99
  randomize_observations: objects
  room_size: l
  rewards:
    correct: 1
    wrong: 0
    partial: 0
  make_everything_static: false
  num_total_questions: 1000
  question_interval: 1
  include_walls_in_observations: true
ddqn: true
dueling_dqn: true
default_root_dir: ./training_results/baselines/dqn_lstm/history_block_size=6
run_handcrafted_baselines: true
